Traceback (most recent call last):
  File "D_fake.py", line 12, in <module>
    from numpy import astype
ImportError: cannot import name 'astype'
